#include <WiFi.h>
#include <esp_wifi.h>
#include <WebSocketsClient.h>
#include "esp_eap_client.h"
#include "./connection.h"

const char* ca_cert = 
"-----BEGIN CERTIFICATE-----\n"
"MIIcAzCCGuugAwIBAgIJQgAAE2FnRQ1eMA0GCSqGSIb3DQEBCwUAMFQxGTAXBgNV\n"
"BAoMEEFPIEthc3BlcnNreSBMYWIxNzA1BgNVBAMMLkthc3BlcnNreSBBbnRpLVZp\n"
"cnVzIFBlcnNvbmFsIFJvb3QgQ2VydGlmaWNhdGUwHhcNMjQwNTI3MjM1MDU0WhcN\n"
"MjUwNTI2MjM1MDU0WjBkMQswCQYDVQQGEwJVUzELMAkGA1UECBMCV0ExEDAOBgNV\n"
"BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEWMBQG\n"
"A1UEAxMNZGV2dHVubmVscy5tczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n"
"ggEBAOtqnpcSxY6WdYF7BGQJ8yK355TzTk9NvxoS4JVfHjafbZpUrLRhxHPoj6Ap\n"
"rlfM6lyOgLhqBQCHp3H5WY8cd8vvy1A7mlOQRyL2fQGDMnLHzyuaTF6YRZEqTWdi\n"
"wosfUz3FCF39oR+FshL63KSlooV7MuRR/pi5OpxqzDu5dSn1N6mBcR/yp4yCil2x\n"
"rBhzt9HT5/li/fSzws29mSdEHM9JXRrlXu3ou0zgvo+MamPIEdaFC4OcYngaaK4y\n"
"MIRII8ma2yco9yixmkV/7TnOxHUzr681KVijBr/tXN9/EExsekGVIISeMdR3casU\n"
"f0w9W7eMGtztey8qESj+8t8ZVpcCAwEAAaOCGMYwghjCMBMGA1UdJQQMMAoGCCsG\n"
"AQUFBwMBMAsGA1UdDwQEAwIFoDAfBgNVHSMEGDAWgBS+6GZmWxhtwhuM7s1q7Zyf\n"
"Eh//eTBlBgNVHREEXjBchwQUWkIHgh50anZkZHM0Yy04MC51a3MxLmRldnR1bm5l\n"
"bHMubXOCDWRldnR1bm5lbHMubXOCDyouZGV2dHVubmVscy5tc4IUKi51a3MxLmRl\n"
"dnR1bm5lbHMubXMwPQYDVR0fBDYwNDAyoDCgLoYsaHR0cDovL2tpcy5jcmwuc2Ny\n"
"Lmthc3BlcnNreS1sYWIuY29tL2NybC5jcmwwghfVBglghkgBhvhCAQ0EghfGFoIX\n"
"wk1JSUloekNDQm0rZ0F3SUJBZ0lUTXdDaW9xRHBPNVRDWFN3NUJRQUFBS0tpb0RB\n"
"TkJna3Foa2lHOXcwQkFRd0ZBREJkTVFzd0NRWURWUVFHRXdKVlV6RWVNQndHQTFV\n"
"RUNoTVZUV2xqY205emIyWjBJRU52Y25CdmNtRjBhVzl1TVM0d0xBWURWUVFERXlW\n"
"TmFXTnliM052Wm5RZ1FYcDFjbVVnVWxOQklGUk1VeUJKYzNOMWFXNW5JRU5CSURB\n"
"ME1CNFhEVEkwTURneU9UQXpORFUxTVZvWERUSTFNRGd5TkRBek5EVTFNVm93WkRF\n"
"TE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBbGRCTVJBd0RnWURWUVFIRXdk\n"
"U1pXUnRiMjVrTVI0d0hBWURWUVFLRXhWTmFXTnliM052Wm5RZ1EyOXljRzl5WVhS\n"
"cGIyNHhGakFVQmdOVkJBTVREV1JsZG5SMWJtNWxiSE11YlhNd2dnRWlNQTBHQ1Nx\n"
"R1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURSMG5BOExkNzlGSU9jUzJy\n"
"ajI0ZkdWYUdaNWZCODludkR5YTQwNXdpRi9GTzA0YjVEUVdIRWRTSXB4THZ1OXlz\n"
"a1FEVituc2wrL0EzdjcyVmlEV3lBWmlwNys5SmhKL0JvUW5yMzlFOVQrb1IwN1Jj\n"
"cFZnZGNMZWxNaVNQcnU0a25vVHB6a2dTVldGdHRKODVtWmIwdExVck15V1Z5elB0\n"
"VU5XaUFrckF0Lzl0Tmt4Mm5LWWtuZ2RiSDBxaEpIZXVSWElvK2JEUnQwY0JpN3Rq\n"
"TTh1bkRjQTYwMjY5bDkxRlVLNTRpOWF2czJBOUJhQzE1VzdSMytlNmMzNCtKL0E2\n"
"V3NlNVdCbEhSbllXMUhlZFhuS2pHVWIvMi8wL0ZiYjB3ZllveGpCWWwzUnZWalp3\n"
"V1BXZlN5MjExOXJUcEhKKy9FUGtGWUphNWg3Q0tlaVNrWFBBVkFnTUJBQUdqZ2dR\n"
"M01JSUVNekNDQVg4R0Npc0dBUVFCMW5rQ0JBSUVnZ0Z2QklJQmF3RnBBSGNBM2R6\n"
"S05KWFg0UllGNTVVeStzZWYrRDBjVU4vYkFEb1VFbllLTEt5N3lDb0FBQUdSbkVh\n"
"TjJnQUFCQU1BU0RCR0FpRUErMldBSGIzRTBoU0dvSUdUVHJMQVYxMi90TnFhR2NF\n"
"OStXcHVBOURpb3FZQ0lRREM5ckJQaXlwejhwcHhUY2tVK0t0NEM0cVpKNHRuUkJP\n"
"OUFNQUQwalVheEFCM0FIMVpIaExoZUNwN0hHRm5mRjc5K05DSFhCU2dUcFdldVFN\n"
"djJRNk1Mbm00QUFBQmtaeEdqWm9BQUFRREFFZ3dSZ0loQVBheEFtV2FMWHR3SjEy\n"
"eDE3SURMQVZmZHNxeStkQVlOZk1BMjBYVGNjSzRBaUVBeVRnWlJOcTNqQUlUaWt4\n"
"NkZCN1RoZGg3OUwyMWF1T0xNZHhsV2VqeDAvOEFkUUFhQlA5SjBGUWRRSy8yb01P\n"
"LzhkakVaeTlPN080alFHaVlheGRBTHR5SmZRQUFBWkdjUm80TUFBQUVBd0JHTUVR\n"
"Q0lFbTJZakE2cmdvSjZySHpIU0wvSVExTG1SNm1LejdxbUJVS29VanMxVkd5QWlC\n"
"dFpKRk1VTHZRL1hSTXN3OFBtZ1FqOXBsd2c1RzRuQWlnMGQzcHNxNEJqekFuQmdr\n"
"ckJnRUVBWUkzRlFvRUdqQVlNQW9HQ0NzR0FRVUZCd01DTUFvR0NDc0dBUVVGQndN\n"
"Qk1Ed0dDU3NHQVFRQmdqY1ZCd1F2TUMwR0pTc0dBUVFCZ2pjVkNJZTkxeHVCNSt0\n"
"R2dvR2RMbzdRRElmdzJoMWRnb1RsYVlMenB6NENBV1FDQVNZd2diUUdDQ3NHQVFV\n"
"RkJ3RUJCSUduTUlHa01ITUdDQ3NHQVFVRkJ6QUNobWRvZEhSd09pOHZkM2QzTG0x\n"
"cFkzSnZjMjltZEM1amIyMHZjR3RwYjNCekwyTmxjblJ6TDAxcFkzSnZjMjltZENV\n"
"eU1FRjZkWEpsSlRJd1VsTkJKVEl3VkV4VEpUSXdTWE56ZFdsdVp5VXlNRU5CSlRJ\n"
"d01EUWxNakF0SlRJd2VITnBaMjR1WTNKME1DMEdDQ3NHQVFVRkJ6QUJoaUZvZEhS\n"
"d09pOHZiMjVsYjJOemNDNXRhV055YjNOdlpuUXVZMjl0TDI5amMzQXdIUVlEVlIw\n"
"T0JCWUVGSStNektkVnZKejZENHJxd2tFa1lrYk5tQWpHTUE0R0ExVWREd0VCL3dR\n"
"RUF3SUZvREEvQmdOVkhSRUVPREEyZ2cxa1pYWjBkVzV1Wld4ekxtMXpnZzhxTG1S\n"
"bGRuUjFibTVsYkhNdWJYT0NGQ291ZFd0ek1TNWtaWFowZFc1dVpXeHpMbTF6TUF3\n"
"R0ExVWRFd0VCL3dRQ01BQXdhZ1lEVlIwZkJHTXdZVEJmb0YyZ1c0WlphSFIwY0Rv\n"
"dkwzZDNkeTV0YVdOeWIzTnZablF1WTI5dEwzQnJhVzl3Y3k5amNtd3ZUV2xqY205\n"
"emIyWjBKVEl3UVhwMWNtVWxNakJTVTBFbE1qQlVURk1sTWpCSmMzTjFhVzVuSlRJ\n"
"d1EwRWxNakF3TkM1amNtd3daZ1lEVlIwZ0JGOHdYVEJSQmd3ckJnRUVBWUkzVElO\n"
"OUFRRXdRVEEvQmdnckJnRUZCUWNDQVJZemFIUjBjRG92TDNkM2R5NXRhV055YjNO\n"
"dlpuUXVZMjl0TDNCcmFXOXdjeTlFYjJOekwxSmxjRzl6YVhSdmNua3VhSFJ0TUFn\n"
"R0JtZUJEQUVDQWpBZkJnTlZIU01FR0RBV2dCUTdjTkZUNlhZbG5XQ295bVlQeHB1\n"
"dWIxUVdhakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQWdZSUt3WUJCUVVIQXdF\n"
"d0RRWUpLb1pJaHZjTkFRRU1CUUFEZ2dJQkFMeVlQeVlUMUwyblEzSFF2NXRvRmVj\n"
"VTVpbDRnWVZXRnBWeE5XUEFtU2trVjFyRHhRVmpFVTdGdE10dGhoMzFoY1VBUkxU\n"
"L2NPaEZxY3I3eEFmcWh2OEZLbWFHK2dJYldOUWRsWWtIaVZDSHgrNVUzdVJ5MUxV\n"
"d2NjNmkwMlVaaXVHRURCTHlXRW9Cemp5UHVjd1U4SW0xdFJqNnlwSFcxeVYwSzhx\n"
"MU90U2o4N3JiOElzakV0SGVycXFJaklBaUtKZ3RmbnMxSDF1ZmlqV2taZkwyU0pu\n"
"UitGeDF6UTcwYU5mSTZvaDlFbFlPTDVSQ3B6MVllWHZ0aU01TEtTUmpBVmV2NWpK\n"
"dlErd00zbTZWUzI4WHpyL25LazJacGdJTTBGTE5MRERTc1RFaWtld1phZkZnbCtj\n"
"c1Irdy9YMjd2WEdjYzlFYk85aE45S25vU2ZXVVZVQ0VaWjBXUnRmUkRpOWx3Q0ha\n"
"eWQ2RnRIcFhFdElncko0dFBmbHR3d0ZDeDdMRWZaTFdldzdiSHkxM1pMT0NRYlZj\n"
"YWhqNS9TbTE2WWJLdEFuTmgvYk9GRzFETUM2WjZSdHJXZEtZZTZ4R2w1TlQxUm40\n"
"YWhLVzJvMEpzeE5VS0lZbFVueTlUcXg5b0hIWGZLL1p4UlFIVU5LVzhRZ0VBMWpy\n"
"RDY0UmtyUHhMYis1YVp1U1VMc0FsVzgzRURnQTBKeFZFbnFTZWNpK2xGczlYYk1N\n"
"dW52Tlp1cHNIZnpoUnRhRFVxV2ZoMm0rUk9nOFM3NjBIUW9GaTUxd2pXYU51Vnkw\n"
"Q2FVb0NkYm8xUUpPTkZpL1d0SEQyRVQ2OHJIZEdFSUQwemdmTmZSaFFpaG9GZjd3\n"
"dVU3Mmp6emdmV1FoVnc5OFJZNnFnZ3NrR1p4OTNGdXZ1OEVsTTtNSUlGckRDQ0JK\n"
"U2dBd0lCQWdJUUNmbHV3cFZWWHlSMG5xOGVYYzdVblRBTkJna3Foa2lHOXcwQkFR\n"
"d0ZBREJoTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNu\n"
"UWdTVzVqTVJrd0Z3WURWUVFMRXhCM2QzY3VaR2xuYVdObGNuUXVZMjl0TVNBd0hn\n"
"WURWUVFERXhkRWFXZHBRMlZ5ZENCSGJHOWlZV3dnVW05dmRDQkhNakFlRncweU16\n"
"QTJNRGd3TURBd01EQmFGdzB5TmpBNE1qVXlNelU1TlRsYU1GMHhDekFKQmdOVkJB\n"
"WVRBbFZUTVI0d0hBWURWUVFLRXhWTmFXTnliM052Wm5RZ1EyOXljRzl5WVhScGIy\n"
"NHhMakFzQmdOVkJBTVRKVTFwWTNKdmMyOW1kQ0JCZW5WeVpTQlNVMEVnVkV4VElF\n"
"bHpjM1ZwYm1jZ1EwRWdNRFF3Z2dJaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQ0R3\n"
"QXdnZ0lLQW9JQ0FRREJlVXkxM2VSWi9RQzViTjcvSU9HeG9kbnk3WG0yQkZjODhk\n"
"M2NjYTN5SHl5VngxWTYwK2FmWTZEQW8vMkxzMXV6QWZiRGZNekFWV0phelBINHRj\n"
"a2FJdER2Ly9odEViYk5KbkFHdlpQQjRWcU52aXdERW1sQVdUL01UQW16WGZUZ1dY\n"
"dVVOZ1Jselpiam9GYVBtK3Q2aUo2SGR2RHBXUUFKYnNCVVpDZ2F0MjU3dE0yOEpu\n"
"QUhVVFdkaURCbisyejZFR2gyREE2QkN4MDR6SERLVlNlZ0xZOCs1UDgwTHF6ZTBk\n"
"NmkzVDJKSjdyZnhDbXhVWGZDR092OWlRSVVaZmh2NHZDYjhoc20vSmROVU1pb21K\n"
"aFNQYTBiaTNyZGEvc3d1SkhDSC8vZHd6MkFHelpSUkdkajdLbmE0dDZUb3hLMTds\n"
"QUYzUTZRcDM2OEM5Y0U2SkxNaiszVWJZM3VtV0NQUkE1L0RtczQvd2wzR3ZERXc3\n"
"SHB5S3N2Uk5QcGpEWnlpRnpaR0MySFptR01zclpNVDNoeG15UXdtejFPM2VHWWRP\n"
"NUVJcTFTVy92VDF5U2haVFN1c3FtSUNRbzVnV1dSWlR3Q0VOZWtTYlZYOXFScjc3\n"
"bzBwakt0dUJNWlRHUVRpeHdwVC9yZ1VsN01yNE0ybnFLNTVLb3Z5L2tVTjF6bmZQ\n"
"ZFcvRmo5aUN1dlBLd0tGZHl0MlJWZ3hKRHZnSUYvYk5vUmtSeGh3VkI2cVJnczRF\n"
"aVRyTmJSb1pBSEVGRjV3UkJmOWdXbjlIZW9JNjZWdGRNWnZKUkgrMC9GRFdCNC96\n"
"d3hTMTZubkFESmFWUFhoNkpISkZZczlwMHdabXZjdDNHTmRXck9MUkFHMnl6YmZG\n"
"WlM4ZkpjWDFQWXhYWG80QnkxNnlHV2hRSURBUUFCbzRJQllqQ0NBVjR3RWdZRFZS\n"
"MFRBUUgvQkFnd0JnRUIvd0lCQURBZEJnTlZIUTRFRmdRVU8zRFJVK2wySloxZ3FN\n"
"cG1EOGFicm05VUZtb3dId1lEVlIwakJCZ3dGb0FVVGlKVUlCaVY1dU51NWcvNity\n"
"a1M3UVlYanprd0RnWURWUjBQQVFIL0JBUURBZ0dHTUIwR0ExVWRKUVFXTUJRR0ND\n"
"c0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQjJCZ2dyQmdFRkJRY0JBUVJxTUdnd0pB\n"
"WUlLd1lCQlFVSE1BR0dHR2gwZEhBNkx5OXZZM053TG1ScFoybGpaWEowTG1OdmJU\n"
"QkFCZ2dyQmdFRkJRY3dBb1kwYUhSMGNEb3ZMMk5oWTJWeWRITXVaR2xuYVdObGNu\n"
"UXVZMjl0TDBScFoybERaWEowUjJ4dlltRnNVbTl2ZEVjeUxtTnlkREJDQmdOVkhS\n"
"OEVPekE1TURlZ05hQXpoakZvZEhSd09pOHZZM0pzTXk1a2FXZHBZMlZ5ZEM1amIy\n"
"MHZSR2xuYVVObGNuUkhiRzlpWVd4U2IyOTBSekl1WTNKc01CMEdBMVVkSUFRV01C\n"
"UXdDQVlHWjRFTUFRSUJNQWdHQm1lQkRBRUNBakFOQmdrcWhraUc5dzBCQVF3RkFB\n"
"T0NBUUVBbzlzSnZCTkxRU0oxZTdWYUczY1NaSEJ6NnpqUzcwQTFnVk8xcHFzbVgz\n"
"NEJXRFB6MVRBbE95SmlMbEErZVVGNEIyT1dIZDNGLy9kSkovM1RhQ0Z1bmpCaFp1\n"
"ZHYzYnVzbDdmbHo0MksvQkcvZU9kbGcwa2lVZjA3UENZWTUvRktZVEljaDUxajFt\n"
"b0ZsQnFiZ2x3a2ROSVZhZTJ0T3UwT2RYMkppQSticHJZY0d4YTdlYXlMZXR2UGlB\n"
"Nzd5blRjVU5NS09xWUI0MUZaSE9YZTVJWERJNXQyUnNETTlkTUVadjQrY09iOUc5\n"
"cVhjZ0RhcjFBelBIRXQvMzkzMzV6Q0hvZlEwUXVJdENEQ0R6YWhXWmNpOU5uOWhi\n"
"L1N2QXRQV0haTGtMQkc2STBpd0d4dk13Y1RUYzlKbmI0Rmx5c3JtUWx3S3NTMk1w\n"
"aE9vSTIzUXEzY1NBPT07TUlJRGpqQ0NBbmFnQXdJQkFnSVFBenJ4NXFjUnFhQzdL\n"
"R1N4SFFuNjVUQU5CZ2txaGtpRzl3MEJBUXNGQURCaE1Rc3dDUVlEVlFRR0V3SlZV\n"
"ekVWTUJNR0ExVUVDaE1NUkdsbmFVTmxjblFnU1c1ak1Sa3dGd1lEVlFRTEV4QjNk\n"
"M2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhi\n"
"RzlpWVd3Z1VtOXZkQ0JITWpBZUZ3MHhNekE0TURFeE1qQXdNREJhRncwek9EQXhN\n"
"VFV4TWpBd01EQmFNR0V4Q3pBSkJnTlZCQVlUQWxWVE1SVXdFd1lEVlFRS0V3eEVh\n"
"V2RwUTJWeWRDQkpibU14R1RBWEJnTlZCQXNURUhkM2R5NWthV2RwWTJWeWRDNWpi\n"
"MjB4SURBZUJnTlZCQU1URjBScFoybERaWEowSUVkc2IySmhiQ0JTYjI5MElFY3lN\n"
"SUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXV6Zk5O\n"
"Tng3YThteWFKQ3RTblgvUnJvaENnaU45UmxVeWZ1STIvT3U4anFKa1R4NjVxc0dH\n"
"bXZQckMzb1hna2tSTHBpbW43V282aCs0RlIxSUFXc1VMZWNZeHBzTU56YUh4bXgx\n"
"eDdlL2RmZ3k1U0RONjdzSDBOTzNYc3MwcjB1cFMva3FiaXRPdFNacExZbDZadHJB\n"
"R0NTWVA5UElVa1k5MmVRcTJFR25JL3l1dW0wNlpJeWE3WHpWK2hkRzgyTUhhdVZC\n"
"SlZKOHpVdGx1TkpiZDEzNC90SlM3U3NWUWVwajVXenRDTzdURzFGOFBhcHNwVXd0\n"
"UDFNVll3blNsY1VmSUtkelhPUzB4WktCZ3lNVU5HUEhnbStGNkhtSWNyOWcrVVF2\n"
"SU9sQ3NSbktQWnpGQlE5Um5iRGh4U0pJVFJOcnc5RkRLWkpvYnE3bk1XeE00TXBo\n"
"UUlEQVFBQm8wSXdRREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIv\n"
"d1FFQXdJQmhqQWRCZ05WSFE0RUZnUVVUaUpVSUJpVjV1TnU1Zy82K3JrUzdRWVhq\n"
"emt3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdCbktKUnZEa2hqNnpIZDZtY1kx\n"
"WWw5UE1XTFNuL3B2dHNyRjkrd1gzTjNLaklUT1lGblFvUWo4a1ZuTmV5SXYvaVBz\n"
"R0VNTktTdUlFeUV4dHY0TmVGMjJkK21RcnZIUkFpR2Z6WjBKRnJhYkEwVVdUVzk4\n"
"a25kdGgvSnN3MUhLajJaTDd0Y3U3WFVJT0daWDFOR0ZkdG9tL0R6TU5VK01lS05o\n"
"SjdqaXRyYWxqNDFFNlZmOFBsd1VIQkhRUkZYR1U3QWo2NEd4SlVURnk4YkpaOTE4\n"
"ckdPbWFGdkU3RkJjZjZJS3NoUEVDQlYxL01VUmVYZ1JQVHFoNVV5a3c3K1UwYjZM\n"
"SjMvaXlLNVM5a0pSYVRlcExpYVdOMGJmVktmamxsRGlJR2tuaWJWYjYzZERjWTNm\n"
"ZTBEa2h2bGQxOTI3anlOeEYxV1c2TFpabTZ6TlRmbE1yWT0wDQYJKoZIhvcNAQEL\n"
"BQADggEBAKCf1mgCx5EqBgqkGWz6t55+n19qVy4LVbjxuXVnudagvHNmmqnEmWBq\n"
"nvUrrZfHNUXc9Lphj/U5lQMfC31NB0KKCpv2WjoBeJu01ueAlBgtsu1uJOon2y2p\n"
"GcqAzvZAntEeL09bYWGZ4bZtrm+3vJtxM12JbUpnzgxunHY942IgW0N5YurP+SxR\n"
"zYx7+5ASfQ1nJE1BgnbwjpqjwX+2BczY12l79XrySqIm7ZUurzsnDaMjznTjBSnB\n"
"czfGk8gH1GLoHF4TfTEnI7RPBCOOk9o4Y+dTImW+hgTgqlL90ZQrKVx5e8g7x4Jc\n"
"do6TfgcAu9SV+9RAAZFRWLtkK6148s8=\n"
"-----END CERTIFICATE-----\n";

bool wifi_wait()
{
    int max_attempts = 30;
    while (WiFi.status() != WL_CONNECTED && max_attempts > 0) {
        delay(500);
        max_attempts--;
    }

    if(WiFi.status() == WL_CONNECTED)
    {
        return true;
    }

    return false;
}

bool wifi_begin_enterprise(char *ssid, char *user, char *pass)
{
    WiFi.mode(WIFI_STA);
    esp_eap_client_set_identity((uint8_t *)user, strlen(user));
    esp_eap_client_set_username((uint8_t *)user, strlen(user));
    esp_eap_client_set_password((uint8_t *)pass, strlen(pass));
    esp_wifi_sta_enterprise_enable();
    WiFi.begin(ssid);

    return wifi_wait();
}

bool wifi_begin(char *ssid, char *pass)
{
    WiFi.mode(WIFI_STA);
    WiFi.begin(ssid, pass);

    return wifi_wait();
}

WebSocketsClient webSocket;
void onWebSocketEvent(WStype_t type, uint8_t *payload, size_t length)
{
    switch (type)
    {
    case WStype_DISCONNECTED:
        Serial.println("Disconnected from WebSocket server");
        break;

    case WStype_CONNECTED:
        Serial.println("Connected to WebSocket server");
        webSocket.sendTXT("Hello from ESP32");
        break;

    case WStype_TEXT:
        Serial.print("Received message: ");
        Serial.println((char *)payload);
        break;

    case WStype_BIN:
        Serial.println("Received binary data");
        break;

    case WStype_PING:
        Serial.println("Received ping");
        break;

    case WStype_PONG:
        Serial.println("Received pong");
        break;

    case WStype_ERROR:
        Serial.println("WebSocket error");
        break;
    }
}

void websocket_begin()
{

#if ESP_ARDUINO_VERSION >= ESP_ARDUINO_VERSION_VAL(3, 0, 4)
    webSocket.beginSslWithBundle(WEBSOCKET_SERVER, 443, "/ws", NULL, 0, "");
#else
    webSocket.beginSslWithBundle(WEBSOCKET_SERVER, 443, "/ws", NULL, "");
#endif
    webSocket.onEvent(onWebSocketEvent);
}

void websocket_write_bin(uint8_t *data, uint16_t length)
{
    webSocket.sendBIN(data, length);
}

void websocket_keepalive()
{
    webSocket.loop();
}

uint8_t baseMac[6];
uint8_t *get_mac_address()
{
    esp_err_t ret = esp_wifi_get_mac(WIFI_IF_STA, baseMac);
    if (ret == ESP_OK)
    {
        return baseMac;
    }
    else
    {
        return 0;
    }
}